import Head from "next/head";
import React from "react";
import Blog from "../components/reusable/Blog";
const blogs = [
    {
        id: 1,
        title: "How to create an online menu for your customers",
        date: "October 15, 2021",
        imgUrl: "https://fleksa.com/wp-content/uploads/2021/10/Online-Menu-for-Restaurants-2.png",
    },
    {
        id: 2,
        title: "Online Ordering System that Gives Restaurants More Control",
        date: "October 15, 2021",
        imgUrl: "https://fleksa.com/wp-content/uploads/2021/10/powered-by-fleksa-2--768x384.png",
    },
    {
        id: 3,
        title: "Top Tips for Being Successful with a Restaurant Webshop",
        date: "October 15, 2021",
        imgUrl: "https://fleksa.com/wp-content/uploads/2021/10/powered-by-fleksa--768x384.png",
    },
    {
        id: 4,
        title: "Top Reasons Why Custom Mobile Apps are a Smart Choice for Restaurants",
        date: "October 15, 2021",
        imgUrl: "https://fleksa.com/wp-content/uploads/2021/10/digital-768x406.png",
    },
];

const posts = [
    {
        id: 1,
        title: "How to create an online menu for your customers",
        date: "October 15, 2021",
    },
    {
        id: 2,
        title: "Online Ordering System that Gives Restaurants More Control",
        date: "October 15, 2021",
    },
    {
        id: 3,
        title: "Top Tips for Being Successful with a Restaurant Webshop",
        date: "October 15, 2021",
    },
    {
        id: 4,
        title: "Top Reasons Why Custom Mobile Apps are a Smart Choice for Restaurants",
        date: "October 15, 2021",
    },
    {
        id: 5,
        title: "Digitalization in the Restaurant: More Customer Focus, Less Administration Chaos",
        date: "October 15, 2021",
    },
];

function blog() {
    return (
        <div>
            <Head>
                <title>Blog | Fleksa</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://fleksa.com/wp-content/uploads/2021/09/cropped-Group-162-32x32.png"
                />
            </Head>
            <div className="bg-main py-8">
                <div className="flex lg:container lg:mx-auto">
                    <div className="hidden md:block bg-secondary text-main p-4 mt-4">
                        <h1 className="text-5xl font-oswald font-bold my-4 text-center">
                            Featured Posts
                        </h1>
                        {posts.map((post) => (
                            <div key={post.id} className="py-4">
                                <p className="text-2xl font-oswald cursor-pointer hover:underline">
                                    {post.title}
                                </p>
                                <p>{post.date}</p>
                            </div>
                        ))}
                    </div>
                    <div className="p-4 bg-main grid gap-8 md:grid-cols-2">
                        {blogs.map((blog) => (
                            <div key={blog.id}>
                                <Blog
                                    title={blog.title}
                                    date={blog.date}
                                    imgUrl={blog.imgUrl}
                                />
                            </div>
                        ))}
                    </div>
                </div>
            </div>
            <div className="bg-secondary text-main p-4 md:hidden">
                <h1 className="text-5xl font-oswald font-bold my-4 text-center">
                    Featured Posts
                </h1>
                {posts.map((post) => (
                    <div key={post.id} className="py-4">
                        <p className="text-2xl font-oswald cursor-pointer hover:underline">
                            {post.title}
                        </p>
                        <p>{post.date}</p>
                    </div>
                ))}
            </div>
        </div>
    );
}

export default blog;
