import Head from "next/head";
import Banner from "../components/Banner";
import Cards from "../components/Cards";
import Navbar from "../components/Navbar";
import Section from "../components/Section";
import Services from "../components/Services";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className="bg-main">
                <Banner />
                <Cards />
                <Services />
                <Section />
            </main>
        </div>
    );
}
