import Head from "next/head";
import Banner from "../components/Banner";
import Cards from "../components/Cards";
import Navbar from "../components/Navbar";
import Review from "../components/Review";
import Reviews from "../components/Reviews";
import Section from "../components/Section";
import Services from "../components/Services";

export default function Home() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link
                    rel="icon"
                    href="https://fleksa.com/wp-content/uploads/2021/09/cropped-Group-162-32x32.png"
                />
            </Head>
            <Navbar />
            <main className="bg-main">
                <Banner />
                <Cards />
                <Services />
                <Section />
                <Reviews />
            </main>
        </div>
    );
}
